# docker-Specify the compose version
version: "3"

services:
  app:
    #Build a Dockerfile in the same directory
    build: .
    #Give the container a name(Any)
    container_name: PyJiB
    #You can keep the container running.
    tty: true
    #Mount the files in the directory to the app directory in the container
    volumes: 
      - ./config:/app/config
      - ./input:/app/input
      - ./output:/app/output
      - ./python-scripts:/app/python-scripts
    #Mount port 1000 on the container side to port 8080 on the host side.
    #ports:
    #  - "8080:8080"